# ASSIGNMENT-3

In [1]:
#1 Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [3]:
import numpy as np

In [4]:
np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [5]:
#2 Accept two lists of 5 elements each from the user.
# Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [25]:
a = []
b = []
for i in range(0,5):
    lst1 = int(input("Enter a number:"))
    lst2 = int(input("Enter element for second list:"))
    a.append(lst1)
    b.append(lst2)
arr1 = np.array(a)
arr2 = np.array(b)
concat = np.concatenate((arr1,arr2))
print("After concatenation:",concat)
s = np.sort(concat)
print("After sorting:", s)

Enter a number:1
Enter element for second list:2
Enter a number:3
Enter element for second list:4
Enter a number:5
Enter element for second list:6
Enter a number:7
Enter element for second list:8
Enter a number:9
Enter element for second list:3
After concatenation: [1 3 5 7 9 2 4 6 8 3]
After sorting: [1 2 3 3 4 5 6 7 8 9]


In [26]:
#3 Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
a = np.array([1,2,3,4,5,6]).reshape(2,3)
a.shape

(2, 3)

In [5]:
a.size

6

In [30]:
#4 How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
# Hint: np.newaxis, np.expand_dims

In [33]:
a = np.arange(12)

In [34]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
a.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [59]:
b = np.arange(12).reshape(6,2)
#print(b[:,np.newaxis])
print(b[np.newaxis, :, np.newaxis, :,np.newaxis])
print(b)
print(b.shape)

[[[[[ 0]
    [ 1]]]


  [[[ 2]
    [ 3]]]


  [[[ 4]
    [ 5]]]


  [[[ 6]
    [ 7]]]


  [[[ 8]
    [ 9]]]


  [[[10]
    [11]]]]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
(6, 2)


In [61]:
a = np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [62]:
print(np.expand_dims(a,0))

[[[0 1 2]
  [3 4 5]]]


In [63]:
print(np.expand_dims(a,0).shape)

(1, 2, 3)


In [7]:
#5 Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack()

In [8]:
a = np.array([1,2,3,4,5,6]).reshape(2,3)
print(np.vstack(a))
print(np.hstack(a))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [9]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.vstack(a))
print(np.hstack(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [65]:
#6 How to get Unique items and counts of unique items

# np.unique function can be used to get the unique items. 
# By passing the argument return_counts=True argument along with the array return the unique items and their counts

In [6]:
arr = np.array([1,1,2,3,4,5,5,6,7])
print(np.unique(arr))
print(np.unique(arr,return_counts=True))


[1 2 3 4 5 6 7]
(array([1, 2, 3, 4, 5, 6, 7]), array([2, 1, 1, 1, 2, 1, 1], dtype=int64))
